In [34]:
import pandas as pd

df = pd.read_csv("hotel_bookings.csv")

In [35]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [36]:
df.shape

(119390, 32)

In [37]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='str')

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 29.1 MB

In [39]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [43]:
df['children'] = df['children'].fillna(0)

df['country'] = df['country'].fillna('Unknown')

df['agent'] = df['agent'].fillna(0)

df['company'] = df['company'].fillna(0)

In [44]:
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

In [45]:
df['total_nights'] = (
    df['stays_in_weekend_nights']
    + df['stays_in_week_nights']
)

In [46]:
df['total_guests'] = (
    df['adults']
    + df['children']
    + df['babies']
)

In [47]:
df['adr'].describe()

count    119390.000000
mean        101.831122
std          50.535790
min          -6.380000
25%          69.290000
50%          94.575000
75%         126.000000
max        5400.000000
Name: adr, dtype: float64

In [48]:
df = df[df['adr'] > 0]

df = df[df['adr'] < 500]

In [49]:
df.duplicated().sum()

np.int64(31813)

In [50]:
df.drop_duplicates(inplace=True)

In [51]:
df['reservation_status_date'] = pd.to_datetime(
    df['reservation_status_date']
)

In [52]:
df.info()

<class 'pandas.DataFrame'>
Index: 85614 entries, 2 to 119389
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           85614 non-null  str
 1   is_canceled                     85614 non-null  int64
 2   lead_time                       85614 non-null  int64
 3   arrival_date_year               85614 non-null  int64
 4   arrival_date_month              85614 non-null  str
 5   arrival_date_week_number        85614 non-null  int64
 6   arrival_date_day_of_month       85614 non-null  int64
 7   stays_in_weekend_nights         85614 non-null  int64
 8   stays_in_week_nights            85614 non-null  int64
 9   adults                          85614 non-null  int64
 10  children                        85614 non-null  float64
 11  babies                          85614 non-null  int64
 12  meal                            85614 non-null  str
 13  country                         85614 non-null  str
 14  market_segment                  85614 non-null  str
 15  distribution_channel            85614 non-null  str
 16  is_repeated_guest               85614 non-null  int64
 17  previous_cancellations          85614 non-null  int64
 18  previous_bookings_not_canceled  85614 non-null  int64
 19  reserved_room_type              85614 non-null  str
 20  assigned_room_type              85614 non-null  str
 21  booking_changes                 85614 non-null  int64
 22  deposit_type                    85614 non-null  str
 23  agent                           85614 non-null  float64
 24  company                         85614 non-null  float64
 25  days_in_waiting_list            85614 non-null  int64
 26  customer_type                   85614 non-null  str
 27  adr                             85614 non-null  float64
 28  required_car_parking_spaces     85614 non-null  int64
 29  total_of_special_requests       85614 non-null  int64
 30  reservation_status              85614 non-null  str
 31  reservation_status_date         85614 non-null  datetime64[us]
 32  total_nights                    85614 non-null  int64
 33  total_guests                    85614 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(17), str(11)
memory usage: 22.9 MB

In [53]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_nights,total_guests
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,1,1.0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,1,1.0
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0.0,0,Transient,98.0,0,1,Check-Out,2015-07-03,2,2.0
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,0.0,0,Transient,107.0,0,0,Check-Out,2015-07-03,2,2.0
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,0.0,0,Transient,103.0,0,1,Check-Out,2015-07-03,2,2.0

In [54]:

df['reservation_status_date'] = pd.to_datetime(
    df['reservation_status_date']
)

In [55]:
df.info

<bound method DataFrame.info of                hotel  is_canceled  lead_time  arrival_date_year  \
2       Resort Hotel            0          7               2015
3       Resort Hotel            0         13               2015
4       Resort Hotel            0         14               2015
6       Resort Hotel            0          0               2015
7       Resort Hotel            0          9               2015
...              ...          ...        ...                ...
119385    City Hotel            0         23               2017
119386    City Hotel            0        102               2017
119387    City Hotel            0         34               2017
119388    City Hotel            0        109               2017
119389    City Hotel            0        205               2017

       arrival_date_month  arrival_date_week_number  \
2                    July                        27
3                    July                        27
4                    July                        27
6                    July                        27
7                    July                        27
...                   ...                       ...
119385             August                        35
119386             August                        35
119387             August                        35
119388             August                        35
119389             August                        35

        arrival_date_day_of_month  stays_in_weekend_nights  \
2                               1                        0
3                               1                        0
4                               1                        0
6                               1                        0
7                               1                        0
...                           ...                      ...
119385                         30                        2
119386                         31                        2
119387                         31                        2
119388                         31                        2
119389                         29                        2

        stays_in_week_nights  adults  ...  company  days_in_waiting_list  \
2                          1       1  ...      0.0                     0
3                          1       1  ...      0.0                     0
4                          2       2  ...      0.0                     0
6                          2       2  ...      0.0                     0
7                          2       2  ...      0.0                     0
...                      ...     ...  ...      ...                   ...
119385                     5       2  ...      0.0                     0
119386                     5       3  ...      0.0                     0
119387                     5       2  ...      0.0                     0
119388                     5       2  ...      0.0                     0
119389                     7       2  ...      0.0                     0

       customer_type     adr required_car_parking_spaces  \
2          Transient   75.00                           0
3          Transient   75.00                           0
4          Transient   98.00                           0
6          Transient  107.00                           0
7          Transient  103.00                           0
...              ...     ...                         ...
119385     Transient   96.14                           0
119386     Transient  225.43                           0
119387     Transient  157.71                           0
119388     Transient  104.40                           0
119389     Transient  151.20                           0

       total_of_special_requests  reservation_status  reservation_status_date  \
2                              0           Check-Out               2015-07-02
3                              0           Check-Out               2015-07-02
4                              1           Check-Out               2015-07-03
6                              0           Check-Out               2015-07-03
7                              1           Check-Out               2015-07-03
...                          ...                 ...                      ...
119385                         0           Check-Out               2017-09-06
119386                         2           Check-Out               2017-09-07
119387                         4           Check-Out               2017-09-07
119388                         0           Check-Out               2017-09-07
119389                         2           Check-Out               2017-09-07

        total_nights total_guests
2                  1          1.0
3                  1          1.0
4                  2          2.0
6                  2          2.0
7                  2          2.0
...              ...          ...
119385             7          2.0
119386             7          3.0
119387             7          2.0
119388             7          2.0
119389             9          2.0

[85614 rows x 34 columns]>

In [56]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_nights,total_guests
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,1,1.0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,1,1.0
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0.0,0,Transient,98.0,0,1,Check-Out,2015-07-03,2,2.0
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,0.0,0,Transient,107.0,0,0,Check-Out,2015-07-03,2,2.0
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,0.0,0,Transient,103.0,0,1,Check-Out,2015-07-03,2,2.0

In [57]:
df.to_csv('cleaned_hotel_bookings.csv', index=False)